name: CD

on: [push]

jobs:
  deploy:
    environment:
      name: production
      user: ${{ secrets.USER }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          environment: production 

      - name: Deploy my app
        run: |
          echo ${{ secrets.USER }}
