name: CD

on: [push]

jobs:
  deploy: 
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main 

      - name: Deploy my app
        run: |
          docker build -t deploy:dev .
