name: CD

on:
  push:
    tags:
      - 1.*.*
      - 2.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: test
        run : echo ${{ secrets.USER }}
